
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaibislopezvara
 */
public class VentanaVolumen extends javax.swing.JDialog {

    /**
     * Creates new form VentanaVolumen
     */
    public VentanaVolumen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configuraVentana();
    }
    
   private void configuraVentana() {
        this.setLocation (200,400);
        this.setResizable(false); //que no se pueda cambiar el tamaño
        this.setTitle("CONVERSOR DE UNIDADES DE VOLUMEN"); //asigna un título
        this.setSize(400,300); //Asigna un tamaño 400,300
        limpiarVentana();
        jComboBoxUnidadesfinales.setSelectedIndex(3);
     }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxUnidadesIniciales = new javax.swing.JComboBox<>();
        jTextFieldValorInicial = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();
        jComboBoxUnidadesfinales = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxUnidadesIniciales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no seleccionado", "mililitros", "centilitros", "litros" }));
        jComboBoxUnidadesIniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnidadesInicialesActionPerformed(evt);
            }
        });

        jTextFieldValorInicial.setText("0");
        jTextFieldValorInicial.setSize(new java.awt.Dimension(80, 126));

        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonAtras.setText("ATRÁS");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabelResultado.setText("0");
        jLabelResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelResultado.setSize(new java.awt.Dimension(80, 126));

        jComboBoxUnidadesfinales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no seleccionado", "mililitros", "centilitros", "litros" }));
        jComboBoxUnidadesfinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnidadesfinalesActionPerformed(evt);
            }
        });

        jLabel1.setText("Convertir de:");

        jLabel2.setText("A:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButtonLimpiar)
                .addGap(33, 33, 33)
                .addComponent(jButtonAtras)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxUnidadesIniciales, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldValorInicial)
                            .addGap(3, 3, 3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(jComboBoxUnidadesfinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonAtras))
                .addGap(69, 69, 69))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxUnidadesIniciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxUnidadesfinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelResultado))
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiarVentana();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    
    private void limpiarVentana() {
        jTextFieldValorInicial.setText("0");
        colorjLabelResultadoON();
        jLabelResultado.setText("0");
        jComboBoxUnidadesIniciales.setSelectedIndex(0);
        jComboBoxUnidadesfinales.setSelectedIndex(0);
   }
    
     private void colorjLabelResultadoON() {
    
        jLabelResultado.setOpaque(true); // Habilita el fondo que por defecto es transparente
        jLabelResultado.setBackground(Color.RED); // Cambia el color de fondo
        jLabelResultado.setForeground(Color.WHITE); // Color del texto
    }
   
     private void calcularResultado(Double valor, Double factorConversion, char format) {
        valor=valor*factorConversion;
        jLabelResultado.setText(String.format("%."+format+"f", valor));
    }
    
     
    private void convertirDesdeMl() {
        Double valor;

        int opcion = (Integer)jComboBoxUnidadesfinales.getSelectedIndex();


       switch (opcion) {
          case 0:
            break;
          case 1:
            jLabelResultado.setText(jTextFieldValorInicial.getText());
            break;
          case 2:
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 0.1,'2');
            break;
          case 3:
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 0.001,'3');
            break;
          default:
            System.out.println("Opción no válida 2");
        }
    }
    
    private void convertirDesdeCl() {
        Double valor;

        int opcion = (Integer)jComboBoxUnidadesfinales.getSelectedIndex();
        
    // String opcion = (String) jComboBoxUnidadesfinales.getSelectedItem();
    
        switch (opcion) {
          case 0: //case "no seleccionado"
            break;
          case 1:  // case "mililitros"
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 10.0,'0');
            break;
          case 2: // case "centilitros"
            jLabelResultado.setText(jTextFieldValorInicial.getText());
            break;
          case 3: // case "litros"
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 0.01,'2');
            break;
          default:
            System.out.println("Opción no válida 2");
        }
    
    }
    
  private void convertirDesdeLt() {
        Double valor;

        int opcion = (Integer)jComboBoxUnidadesfinales.getSelectedIndex();
        switch (opcion) {
          case 0:
            break;
          case 1:
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 1000.0,'0');
            break;
          case 2:
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 100.0,'0');
            break;
          case 3:
            jLabelResultado.setText(jTextFieldValorInicial.getText());
            break;
          default:
            break;
        }    
    
    }
   
    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jComboBoxUnidadesfinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnidadesfinalesActionPerformed
       int opcion = (Integer)jComboBoxUnidadesIniciales.getSelectedIndex();  
       if (!jTextFieldValorInicial.getText().trim().equals("0"))
         switch (opcion) {
           case 0:
             break;
           case 1:
            convertirDesdeMl();
            break;
          case 2:
            convertirDesdeCl();
            break;
          case 3:
            convertirDesdeLt();
            break;
          default:
            break;
         }
    }//GEN-LAST:event_jComboBoxUnidadesfinalesActionPerformed

    private void jComboBoxUnidadesInicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnidadesInicialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnidadesInicialesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaVolumen dialog = new VentanaVolumen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBoxUnidadesIniciales;
    private javax.swing.JComboBox<String> jComboBoxUnidadesfinales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JTextField jTextFieldValorInicial;
    // End of variables declaration//GEN-END:variables
}
