
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaibislopezvara
 */
public class VentanaLongitud extends javax.swing.JDialog {
    
    /**
     * Creates new form VentanaLongitud
     */
    public VentanaLongitud(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configuraVentana();
    }

   private void configuraVentana() {
        this.setLocation (200,400);
        this.setResizable(false); //que no se pueda cambiar el tamaño
        this.setTitle("CONVERSOR DE UNIDADES DE LONGITUD"); //asigna un título
        this.setSize(400,300); //Asigna un tamaño 400,300
        limpiarVentana();
     }
   
      private void limpiarVentana() {
        jTextFieldValorInicial.setText("0");
        colorjLabelResultadoON();
        jLabelResultado.setText("0");
        jComboBoxUnidadesIniciales.setSelectedIndex(0);
        jComboBoxUnidadesfinales.setSelectedIndex(0);
   }
   
    //private void colorjLabelResultadoOFF() {
     //  jLabelResultado.setForeground(UIManager.getColor("Label.foreground"));
    //   jLabelResultado.setBackground(UIManager.getColor("Label.background"));
     //  jLabelResultado.setOpaque(false); // Para volver a hacerlo transparente
   // }
    
    
    private void colorjLabelResultadoON() {
    
        jLabelResultado.setOpaque(true); // Habilita el fondo que por defecto es transparente
        jLabelResultado.setBackground(Color.BLUE); // Cambia el color de fondo
        jLabelResultado.setForeground(Color.WHITE); // Color del texto
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxUnidadesIniciales = new javax.swing.JComboBox<>();
        jComboBoxUnidadesfinales = new javax.swing.JComboBox<>();
        jTextFieldValorInicial = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();
        jButtonConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAtras.setText("ATRÁS");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Convertir de:");

        jLabel2.setText("A:");

        jComboBoxUnidadesIniciales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no seleccionado", "centímetros", "metros", "kilometros", " " }));

        jComboBoxUnidadesfinales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no seleccionado", "centímetros", "metros", "kilometros", " " }));

        jTextFieldValorInicial.setText("0");
        jTextFieldValorInicial.setSize(new java.awt.Dimension(80, 126));

        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jLabelResultado.setText("0");
        jLabelResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelResultado.setSize(new java.awt.Dimension(80, 126));

        jButtonConvertir.setText("CONVERTIR");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxUnidadesIniciales, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldValorInicial)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jComboBoxUnidadesfinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonConvertir)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar)
                .addGap(27, 27, 27)
                .addComponent(jButtonAtras)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUnidadesIniciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUnidadesfinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResultado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtras)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonConvertir))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed


    
    private void calcularResultado(Double valor, Double factorConversion, char format) {
            valor=valor*factorConversion;
            //colorjLabelResultadoON();
            jLabelResultado.setText(String.format("%."+format+"f", valor));
    }
    
    
    private void convertirDesdeCM() {   // conversión desde centímetros
        Double valor;

        int opcion = (Integer)jComboBoxUnidadesfinales.getSelectedIndex();


       switch (opcion) {
          case 0: // Opción no seleccionado
            break;
          case 1: // Opción centrímetros
            jLabelResultado.setText(jTextFieldValorInicial.getText());
            break;
          case 2: // Opción metros
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 0.01,'2');
            break;
          case 3: // Opción kilómetros
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 0.00001,'5');
            break;
          default:
            System.out.println("Opción no válida 2");
        }
    }
    
    private void convertirDesdeM() { // conversión desde metros
        Double valor;

        int opcion = (Integer)jComboBoxUnidadesfinales.getSelectedIndex();
    
        switch (opcion) {
          case 0:
            break;
          case 1: // Opción centímetros
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 100.0,'0');
            break;
          case 2: // Opción metros
            jLabelResultado.setText(jTextFieldValorInicial.getText());
            break;
          case 3: // Opción kilómetros
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 0.001,'3');
            break;
          default:
            System.out.println("Opción no válida 2");
        }
    
    }
    
    private void convertirDesdeKM() { // conversión desde kilómetros
        Double valor;

        int opcion = (Integer)jComboBoxUnidadesfinales.getSelectedIndex();
        switch (opcion) {
          case 0:
            break;
          case 1:
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 100000.0,'0');
            break;
          case 2:
            valor = Double.parseDouble(jTextFieldValorInicial.getText());
            calcularResultado(valor, 1000.0,'0');
            break;
          case 3:
            jLabelResultado.setText(jTextFieldValorInicial.getText());
            break;
          default:
            break;
        }    
    
    }
    
    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
       int opcion = (Integer)jComboBoxUnidadesIniciales.getSelectedIndex();
       
       if (!jTextFieldValorInicial.getText().trim().equals("0"))
         switch (opcion) {
           case 0: // NO SELECCIONA
             break;
           case 1: // Opción centrímetro
            convertirDesdeCM();
            break;
          case 2: //Opción es metros
            convertirDesdeM();
            break;
          case 3: // Opción 4 es kilómnetros
            convertirDesdeKM();
            break;
          default:
            break;
         }

    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiarVentana();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLongitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLongitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLongitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLongitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaLongitud dialog = new VentanaLongitud(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBoxUnidadesIniciales;
    private javax.swing.JComboBox<String> jComboBoxUnidadesfinales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldValorInicial;
    // End of variables declaration//GEN-END:variables
}
