
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaibislopezvara
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        configuraVentana();
    }
    
    private void configuraVentana() {
         this.setLocationRelativeTo(null);
         this.setTitle("CONVERSOR DE UNIDADES");
         this.setSize(400,400);
         this.setResizable(false); //que no se pueda cambiar el tamaño
         this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); //Desactiva el botón Finalizr superior
         this.getContentPane().setBackground(Color.YELLOW); //cambiar el color de fondo
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLongitud = new javax.swing.JButton();
        jButtonVolumen = new javax.swing.JButton();
        jButtonInformacion = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 2, 0));

        jButtonLongitud.setText("LONGITUD");
        jButtonLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLongitudActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLongitud);

        jButtonVolumen.setText("VOLUMEN");
        jButtonVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolumenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolumen);

        jButtonInformacion.setText("INFORMACIÓN");
        jPanel1.add(jButtonInformacion);

        jButtonFinalizar.setText("FINALIZAR");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFinalizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLongitudActionPerformed
        // TODO add your handling code here:
        VentanaLongitud vLongitud = new VentanaLongitud(this,false);
        vLongitud.setVisible(true);
    }//GEN-LAST:event_jButtonLongitudActionPerformed

    private void jButtonVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolumenActionPerformed
        // TODO add your handling code here:
        VentanaVolumen vVolumen = new VentanaVolumen(this,false);
        vVolumen.setVisible(true);
    }//GEN-LAST:event_jButtonVolumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonInformacion;
    private javax.swing.JButton jButtonLongitud;
    private javax.swing.JButton jButtonVolumen;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
