/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author LABORATORIOS
 */
public class VentanaResultados extends javax.swing.JDialog {
    
    public VentanaInicio ventanaInicio;

    /**
     * Creates new form VentanaResultados
     */
    public VentanaResultados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ventanaInicio=(VentanaInicio)parent;
        initComponents();
        inicializaVentanaResultados();
    }

     private void inicializaVentanaResultados() {
        this.setLocation(1000,600);
        this.setTitle("RESULTADOS IMC");
        jLabelSaludo.setText(""); 
        jLabelIMC.setText(""); 
        jLabelComposicion.setText(""); 
     }
     
     public void calculayescribeResultados(String nombre, String peso, String altura) {
           //Convertir peso y altura de String a Double
           Double pesoNumerico = Double.parseDouble(peso);
           Double alturaNumerica = Double.parseDouble(altura);
           
           //Convertir de centímetros a metros
           alturaNumerica=alturaNumerica/100;
           
           // Calcular IMC
           Double imc = pesoNumerico / (alturaNumerica*alturaNumerica);
           
           //Redondear con un lugar decimal
           imc = Math.round(imc * 100.0) / 100.0;
           
           String composicion="";
           
           //Identificar composición muscular
           if (imc < 18.5) 
                composicion = "Peso inferior al normal";
           else if (imc < 25) 
                        composicion = "Composición corporal normal";
                else if (imc < 30) 
                        composicion = "Peso superior al normal";
                     else 
                        composicion = "Obesidad";

     
           // Asignar textos a la etiqueta
           
           jLabelSaludo.setText("Estimado/Estimada "+nombre);
           jLabelIMC.setText("Su índice de masa muscular es: "+String.valueOf(imc));
           jLabelComposicion.setText("Su compoaición es: "+composicion);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaludo = new javax.swing.JLabel();
        jLabelIMC = new javax.swing.JLabel();
        jLabelComposicion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSaludo.setText("jLabel1");

        jLabelIMC.setText("jLabel2");

        jLabelComposicion.setText("jLabel3");

        jButton1.setText("ATRÁS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelComposicion)
                            .addComponent(jLabelIMC)
                            .addComponent(jLabelSaludo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton1)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabelSaludo)
                .addGap(37, 37, 37)
                .addComponent(jLabelIMC)
                .addGap(38, 38, 38)
                .addComponent(jLabelComposicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ventanaInicio.limpiaCampos();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaResultados dialog = new VentanaResultados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelComposicion;
    private javax.swing.JLabel jLabelIMC;
    private javax.swing.JLabel jLabelSaludo;
    // End of variables declaration//GEN-END:variables
}
